// AUTO-GENERATED by promptrig.compiler.codegen.typescript. Do not edit by hand.
// Source: https://promptrig.dev/schemas/diagnostic/0.1.0

export interface DiagnosticSource {
  document: string;
  json_pointer: string;
  line?: number;
  column?: number;
}

export interface DiagnosticRelatedItem {
  document: string;
  json_pointer: string;
}

export interface DiagnosticDetails {
  [key: string]: unknown;
}

export interface Diagnostic {
  contract_version: "0.1.0";
  id: string;
  code: string;
  severity: "info" | "warning" | "error";
  phase: "normalization" | "validation" | "optimization" | "capability_resolution" | "safety" | "adapter_lowering" | "cli" | "environment";
  message: string;
  source: DiagnosticSource;
  related?: DiagnosticRelatedItem[];
  hint?: string;
  details?: DiagnosticDetails;
  fingerprint: string;
  caused_by?: string[];
}
