// AUTO-GENERATED by promptrig.compiler.codegen.typescript. Do not edit by hand.
// Source: https://promptrig.dev/schemas/ir/0.1.0

export type NonEmpty = string;
export type Identifier = string;
export type Sha256 = string;
export type NonEmptyStringArray = NonEmpty[];
export type Capabilities = string[];

export interface JsonSchema {
  [key: string]: unknown;
}

export interface DataContract {
  id: Identifier;
  name: NonEmpty;
  required: boolean;
  schema: JsonSchema;
}

export interface Requirement {
  id: string;
  statement: NonEmpty;
  priority: "p0" | "p1" | "p2";
  mandatory: boolean;
  acceptance: NonEmptyStringArray;
}

export interface PolicyBlock {
  rules: NonEmptyStringArray;
}

export interface PromptRigIRProject {
  name: NonEmpty;
  description?: string;
  mode: "creative" | "balanced" | "enterprise";
  compilation_level: "prompt" | "prompt_system" | "agent_blueprint" | "application_specification";
}

export interface PromptRigIRObjective {
  goal: NonEmpty;
  target_users: NonEmptyStringArray;
  success_criteria: NonEmptyStringArray;
  failure_conditions: NonEmptyStringArray;
}

export interface PromptRigIRBehavior {
  instructions: NonEmptyStringArray;
  constraints: NonEmptyStringArray;
  uncertainty_policy: NonEmpty;
  evidence_policy: NonEmpty;
}

export interface PromptRigIRKnowledgeSourcesItem {
  id: Identifier;
  kind: "inline" | "file" | "retrieval_snapshot";
  required: boolean;
  sha256?: Sha256;
}

export interface PromptRigIRKnowledge {
  sources: PromptRigIRKnowledgeSourcesItem[];
}

export interface PromptRigIRMemory {
  mode: "none" | "session" | "persistent";
  retention: NonEmpty;
  sensitive_data_allowed?: boolean;
}

export interface PromptRigIRToolsItem {
  id: Identifier;
  description: NonEmpty;
  input_schema: JsonSchema;
  output_schema?: JsonSchema;
  side_effecting: boolean;
  approval: "never" | "policy" | "always";
}

export interface PromptRigIRWorkflowStepsItem {
  id: Identifier;
  action: NonEmpty;
  on_failure: "stop" | "continue" | "request_approval";
}

export interface PromptRigIRWorkflow {
  steps: PromptRigIRWorkflowStepsItem[];
}

export interface PromptRigIRAutonomy {
  approval_policy: "read_only" | "bounded_write" | "human_approval";
  max_tool_calls: number;
  stop_conditions?: NonEmptyStringArray;
}

export interface PromptRigIRProviderRequirements {
  required_capabilities: Capabilities;
  optional_capabilities: Capabilities;
}

export interface PromptRigIREvaluation {
  dimensions: NonEmptyStringArray;
  repair_limit: number;
  baseline_required: boolean;
  test_categories: NonEmptyStringArray;
}

export interface PromptRigIRDeployment {
  targets: NonEmptyStringArray;
}

export interface PromptRigIRProvenance {
  source_id: NonEmpty;
  source_sha256: Sha256;
}

export interface PromptRigIR {
  spec_version: "0.1.0";
  project: PromptRigIRProject;
  objective: PromptRigIRObjective;
  requirements: Requirement[];
  input_contracts?: DataContract[];
  output_contracts?: DataContract[];
  behavior: PromptRigIRBehavior;
  knowledge?: PromptRigIRKnowledge;
  memory?: PromptRigIRMemory;
  tools?: PromptRigIRToolsItem[];
  workflow?: PromptRigIRWorkflow;
  autonomy?: PromptRigIRAutonomy;
  security?: PolicyBlock;
  privacy?: PolicyBlock;
  provider_requirements?: PromptRigIRProviderRequirements;
  evaluation: PromptRigIREvaluation;
  deployment?: PromptRigIRDeployment;
  assumptions?: NonEmpty[];
  open_questions?: NonEmpty[];
  provenance: PromptRigIRProvenance;
}
